
import Koneksi.Conek;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;

public class register extends javax.swing.JFrame {
    public Connection con;
    public Statement stt;
    public ResultSet rs;
    
    public Dashboard_admin supervisior;
    public Dashboard_Kasir kasir;

    public register() {
        initComponents();
        t_id.requestFocus();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_password = new javax.swing.JPasswordField();
        comboboxjabatan = new javax.swing.JComboBox<>();
        register = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        register1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        t_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t_karyawan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_password.setBackground(new java.awt.Color(211, 211, 211));
        t_password.setForeground(new java.awt.Color(0, 0, 0));
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 200, 30));

        comboboxjabatan.setBackground(new java.awt.Color(255, 255, 255));
        comboboxjabatan.setForeground(new java.awt.Color(0, 0, 0));
        comboboxjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "kasir" }));
        comboboxjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxjabatanActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 200, 30));

        register.setBackground(new java.awt.Color(255, 102, 0));
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("REGISTER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Who_Hd_Transparent__A_Woman_Who_Is_Doing_Makeup__Girl__Makeup__Powder_PNG_Image_For_Free_Download-removebg-preview 1.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 300, 30));

        background.setBackground(new java.awt.Color(255, 204, 204));
        background.setForeground(new java.awt.Color(255, 204, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 109.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SILAHKAN ISI DATA!!!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, 60));

        register1.setBackground(new java.awt.Color(153, 153, 0));
        register1.setForeground(new java.awt.Color(255, 255, 255));
        register1.setText("login");
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });
        jPanel3.add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("sudah punya akun?");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("id RFID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 50, 30));

        t_username.setBackground(new java.awt.Color(211, 211, 211));
        t_username.setForeground(new java.awt.Color(0, 0, 0));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        jPanel3.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 200, 30));

        t_id.setBackground(new java.awt.Color(211, 211, 211));
        t_id.setForeground(new java.awt.Color(0, 0, 0));
        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_idFocusLost(evt);
            }
        });
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        jPanel3.add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 200, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Karyawan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 30));

        t_karyawan.setBackground(new java.awt.Color(211, 211, 211));
        t_karyawan.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(t_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 162, 200, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Username ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 80, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Jabatan ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 80, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String username=t_username.getText();
        if(username.equals("id")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String username=t_username.getText();
        if(username.equals("")||username.equals("id")){
            t_username.setText("id");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String pass=t_password.getText();
        if(pass.equals("*****")){
            t_password.setText("");
        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String pass=t_password.getText();
        if(pass.equals("")||pass.equals("*****")){
            t_password.setText("*****");
        }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
       try {
        // Persiapkan koneksi ke database
        java.sql.Connection conn = Conek.GetConnection();
        
        // Validasi panjang username dan password
        String username = t_username.getText();
        String password = t_password.getText();
        if (username.length() > 20) {
            JOptionPane.showMessageDialog(null, "Panjang username maksimum adalah 20 karakter.");
            return;
        }
        if (password.length() > 8) {
            JOptionPane.showMessageDialog(null, "Panjang password maksimum adalah 8 karakter.");
            return;
        }
        // Query untuk memeriksa apakah jabatan yang dipilih ada dalam database
        String jabatan = comboboxjabatan.getSelectedItem().toString();
        String checkJabatanQuery = "SELECT * FROM jabatan_karyawan WHERE jabatan = ?";
        PreparedStatement pstCheckJabatan = conn.prepareStatement(checkJabatanQuery);
        pstCheckJabatan.setString(1, jabatan);
        ResultSet rsCheckJabatan = pstCheckJabatan.executeQuery();

        // Jika jabatan tidak ditemukan dalam database, tampilkan pesan kesalahan
        if (!rsCheckJabatan.next()) {
            JOptionPane.showMessageDialog(null, "Jabatan yang dipilih tidak tersedia.");
            return;
        }
        
        // Query untuk memeriksa apakah ID karyawan sudah ada dalam database
        String checkIdQuery = "SELECT * FROM login_admin WHERE id_karyawan = ?";
        PreparedStatement pstCheckId = conn.prepareStatement(checkIdQuery);
        pstCheckId.setString(1, t_karyawan.getText());
        ResultSet rsCheckId = pstCheckId.executeQuery();

        // Jika ID karyawan sudah ada dalam database, tampilkan pesan kesalahan
        if (rsCheckId.next()) {
            JOptionPane.showMessageDialog(null, "ID karyawan sudah ada dalam database. Silakan gunakan ID karyawan lain.");
            return;
        }

        // Query untuk memeriksa apakah nama pengguna sudah ada dalam database
        String checkUserQuery = "SELECT * FROM login_admin WHERE username = ?";
        PreparedStatement pstCheckUser = conn.prepareStatement(checkUserQuery);
        pstCheckUser.setString(1, t_username.getText());
        ResultSet rsCheckUser = pstCheckUser.executeQuery();

        // Jika nama pengguna sudah ada dalam database, tampilkan pesan kesalahan
        if (rsCheckUser.next()) {
            JOptionPane.showMessageDialog(null, "Nama pengguna sudah ada dalam database. Silakan pilih nama pengguna lain.");
            return;
        }

        // Jika ID karyawan dan nama pengguna belum ada dalam database, lanjutkan proses penyimpanan data
        String sqlLogin = "INSERT INTO login_admin (id, id_karyawan, username, password, level) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstLogin = conn.prepareStatement(sqlLogin);
        pstLogin.setString(1, t_id.getText());
        pstLogin.setString(2, t_karyawan.getText());
        pstLogin.setString(3, t_username.getText());
        pstLogin.setString(4, t_password.getText());
        pstLogin.setString(5, comboboxjabatan.getSelectedItem().toString());
        pstLogin.executeUpdate();

        // Tampilkan pesan sukses dan atur visibilitas frame
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        this.setVisible(false);
        new login_admin().setVisible(true);

        // Tutup PreparedStatement dan koneksi ke database
        pstLogin.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tolong masukkan data yang benar!!");
    }
    }//GEN-LAST:event_registerActionPerformed

    private void comboboxjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxjabatanActionPerformed

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login_admin().setVisible(true);
    }//GEN-LAST:event_register1ActionPerformed

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idFocusGained

    private void t_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idFocusLost

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> comboboxjabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton register;
    private javax.swing.JButton register1;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_karyawan;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
